import type { Agent, Mission } from './types';

export const agents: Agent[] = [
  {
    id: 'agt-001',
    name: 'Alex "Fantôme" Johnson',
    email: 'alex.j@e-brigade.com',
    skills: ['Surveillance', 'Infiltration', 'Combat'],
    availability: 'Disponible',
    avatarUrl: 'https://picsum.photos/seed/1/200/200',
  },
  {
    id: 'agt-002',
    name: 'Maria "Phénix" Garcia',
    email: 'maria.g@e-brigade.com',
    skills: ['Piratage', 'Cryptographie', 'Analyse de renseignements'],
    availability: 'En mission',
    avatarUrl: 'https://picsum.photos/seed/2/200/200',
  },
  {
    id: 'agt-003',
    name: 'Sam "Vipère" Chen',
    email: 'sam.c@e-brigade.com',
    skills: ['Démolitions', 'Combat rapproché', 'Déminage'],
    availability: 'Disponible',
    avatarUrl: 'https://picsum.photos/seed/3/200/200',
  },
  {
    id: 'agt-004',
    name: 'Isabelle "Muse" Dubois',
    email: 'isabelle.d@e-brigade.com',
    skills: ['Linguistique', 'Interrogatoire', 'Opérations psychologiques'],
    availability: 'Disponible',
    avatarUrl: 'https://picsum.photos/seed/4/200/200',
  },
  {
    id: 'agt-005',
    name: 'Kenji "Ombre" Tanaka',
    email: 'kenji.t@e-brigade.com',
    skills: ['Furtivité', 'Reconnaissance', 'Tir de précision'],
    availability: 'En congé',
    avatarUrl: 'https://picsum.photos/seed/5/200/200',
  },
];

export const missions: Mission[] = [
  {
    id: 'msn-001',
    name: 'Opération Crépuscule',
    location: 'Genève, Suisse',
    startDate: new Date('2024-08-15T09:00:00'),
    endDate: new Date('2024-08-20T17:00:00'),
    requiredSkills: ['Piratage', 'Surveillance'],
    assignedAgents: [agents[1]],
    status: 'En cours',
  },
  {
    id: 'msn-002',
    name: 'Projet Chimère',
    location: 'Tokyo, Japon',
    startDate: new Date('2024-09-01T09:00:00'),
    endDate: new Date('2024-09-10T17:00:00'),
    requiredSkills: ['Infiltration', 'Combat', 'Démolitions'],
    assignedAgents: [],
    status: 'Planification',
  },
  {
    id: 'msn-003',
    name: 'Opération Serpent Silencieux',
    location: 'Le Caire, Égypte',
    startDate: new Date('2024-07-01T09:00:00'),
    endDate: new Date('2024-07-05T17:00:00'),
    requiredSkills: ['Linguistique', 'Furtivité'],
    assignedAgents: [agents[3], agents[4]],
    status: 'Terminée',
  },
  {
    id: 'msn-004',
    name: 'Initiative Renard Arctique',
    location: 'Svalbard, Norvège',
    startDate: new Date('2024-10-10T09:00:00'),
    endDate: new Date('2024-10-15T17:00:00'),
    requiredSkills: ['Survie', 'Reconnaissance'],
    assignedAgents: [],
    status: 'Planification',
  },
];
